### ISSUE TITLE
Malformed DB using fts5

### ISSUE THREAD

**Issue by theboolean** [vlcn-io/js#31] opened 2023-10-10 08:22 UTC
Hi!
I think I found a blocking bug for `@vlcn.io/crsqlite-wasm` when using `fts5`.

Basically after some INSERT I receive this error and the db becomes unusable:

```
Error: database disk image is malformed
    at check (sqlite-api.js:866:1)
    at Object.step (sqlite-api.js:699:1)
    at async TX.statements (TX.ts:152:1)
```

I saw this can be mitigated by wrapping the INSERT into a transaction, but still if you perform lot of transactions this happens again.

Minimal code to reproduce:

```
    const sqlite = await initWasm()
    const db = await sqlite.open('sqlite_test.db')
    await db.exec('CREATE VIRTUAL TABLE IF NOT EXISTS test_fts USING fts5(fieldA, fieldB, fieldC, fieldD, fieldE, id UNINDEXED, prefix=2, detail=none);')

    for (let i = 0; i < 1000; i++) {
      await db.exec(`INSERT INTO test_fts (fieldA, fieldB, fieldC, fieldD, fieldE, id) VALUES ('test', 'test', 'test', 'test', 'test', '${i}');`)
        .catch(err => {
          console.error(err, i)
        })
    }
```

to me it always fail during iteration 877.

I also created a basic [create-react-app project](https://github.com/theboolean/sqlite-test) that demonstrates this, code lives [here](https://github.com/theboolean/sqlite-test/blob/main/src/App.js).

**Comment by theboolean** [comment] 2023-10-10 08:26
Forgot to say: tested in Chrome and Firefox on Mac OS

**Comment by tantaman** [comment] 2023-10-11 16:19
Thanks for the report. It may be a problematic interaction with the indexeddb vfs. I should release a variant of cr-sqlite that lets the user choose their virtual filesystem so we can track these things down.

**Comment by theboolean** [comment] 2023-10-11 16:22
FYI I tried to set the DB in memory and the error didn't occur, so you're right: it must be something related to indexeddb. Did you manage to reproduce the bug on your side?

**Comment by AlexErrant** [comment] 2023-10-12 14:36
>I found a blocking bug

In the interest of getting you unblocked, have you tried inserting multiple values at a time, e.g.

```sql
INSERT INTO test_fts (
  fieldA, fieldB, fieldC, fieldD, fieldE, 
  id
) 
VALUES 
  (
    'test', 'test', 'test', 'test', 'test', 
    '${i}'
  ), 
  (
    'test', 'test', 'test', 'test', 'test', 
    '${i}'
  ), 
  (
    'test', 'test', 'test', 'test', 'test', 
    '${i}'
  ), 
  (
    'test', 'test', 'test', 'test', 'test', 
    '${i}'
  ), 
  (
    'test', 'test', 'test', 'test', 'test', 
    '${i}'
  );
```

I do this in my own project [here](https://github.com/AlexErrant/Pentive/blob/31bed52e9493cfdf7deab1d2c14d7f250a4842b0/app/src/sqlite/note.ts#L123-L130) in batches of 1000 and was able to add ~35k rows without `database disk image is malformed` (I really should use a transaction though). Schema [here](https://github.com/AlexErrant/Pentive/blob/31bed52e9493cfdf7deab1d2c14d7f250a4842b0/shared/src/index.ts#L19-L66) - I only have 3 FTS columns though compared to your example's 5. If you want to test my code I can upload those rows somewhere.

**Comment by theboolean** [comment] 2023-10-16 15:58
Unfortunately, this is not a workaround we can implement with our use case. We perform lot of updates after the first db population, and eventually it will corrupt

**Comment by tantaman** [comment] 2023-10-16 16:31
@theboolean - would switching to OPFS be acceptable for your use case? I think the OPFS VFS should handle this fine since it is less temperamental than indexeddb.

@rhashimoto - just an fyi. I assume this is in wa-sqlite itself but haven't stripped out cr-sqlite layers to confirm.

**Comment by rhashimoto** [comment] 2023-10-16 16:54
@theboolean If you run your test with Dev Tools open is there anything interesting printed to the console when it fails?

**Comment by theboolean** [comment] 2023-10-17 07:52
@tantaman I would like to use indexeddb because of wider browser support, but I can give OPFS a try to compare performances.

@rhashimoto the only error I receive is the one I pasted in the OP, but I added the repo that can reproduce the issue to [codesandbox](https://codesandbox.io/p/github/theboolean/sqlite-test/main), so you can try by yourself.

Thank you guys for the interest in this issue 🙏🏻

**Comment by theboolean** [comment] 2023-10-27 13:24
@tantaman is exposing OPFS a simple change to do?

**Comment by tantaman** [comment] 2023-10-27 17:48
@theboolean - should be pretty straightforward. Would be a matter of exposing an option for the user to supply a VFS class to `initWasm`

See these lines:

https://github.com/vlcn-io/js/blob/705f6d2409d84c58c7953276e6b9102c2c08501b/packages/crsqlite-wasm/src/index.ts#L55-L57

https://github.com/vlcn-io/js/blob/705f6d2409d84c58c7953276e6b9102c2c08501b/packages/crsqlite-wasm/src/index.ts#L39-L57

**Comment by rhashimoto** [comment] 2023-10-29 02:39
I [can't reproduce this with wa-sqlite](https://github.com/rhashimoto/wa-sqlite/issues/118) using the SQL in the original post. I bumped the number of iterations up to 100,000 without seeing an error.

I think the next step is probably for someone (not me) to check whether the problem is reproducible in the fork of wa-sqlite.

**Comment by rhashimoto** [comment] 2023-10-29 14:42
Reproduced in wa-sqlite. It fails with SQLITE_CORRUPT on iteration 877, exactly as reported.

**Comment by rhashimoto** [comment] 2023-10-30 00:04
It's a bug in IDBBatchAtomicVFS. It also reveals a [likely bug in SQLite](https://sqlite.org/forum/forumpost/7823af6ccb), without which it probably wouldn't have shown up here. It's still a critical bug in IDBBatchAtomicVFS, though, as I think it can be exposed in other ways. I hope to merge the fix tomorrow-ish.

**Comment by tantaman** [comment] 2023-10-30 13:53
Appreciate it.

@theboolean  - I'll roll a new release to update to https://github.com/rhashimoto/wa-sqlite/releases/tag/v0.9.8 which will resolve this issue.

**Comment by rhashimoto** [comment] 2023-10-30 14:09
@theboolean What a great bug report, including a compact reproduction! This exposed not one but two quite subtle bugs, one in SQLite which is possibly the best tested library on the planet (and one in wa-sqlite which is...not). The bug was fixed in SQLite only hours after submission, and was considered important enough to bypass the code freeze for their imminent release.

**Comment by theboolean** [comment] 2023-11-05 14:32
@tantaman I think it makes sense to merge wa-sqlite v0.9.8 as a patch and then releasing v0.16. What do you think?

**Comment by iansinnott** [comment] 2023-11-05 14:51
> @theboolean, @iansinnott - do you guys need a fix immediately or can you wait till the v0.16 release?

@tantaman no rush, thanks for looking into this

**Comment by tantaman** [comment] 2023-11-06 13:59
This'll fix it -- https://github.com/vlcn-io/js/pull/36

but I'll need to publish a new release for everyone.

**Comment by theboolean** [comment] 2023-11-27 11:00
Hi @tantaman! Touching base just to check if there are any updates on this :)

**Comment by tantaman** [comment] 2023-11-27 14:20
@theboolean - I'll be publishing a new release today. Luckily it'll be compatible with the current release as we decided to revert some breaking changes.

**Comment by tantaman** [comment] 2023-11-27 20:29
re-opening until the release is actually published.

**Comment by tantaman** [comment] 2023-11-27 22:21
Almost there. Need to get this pulled in -- https://github.com/vlcn-io/js/pull/38

**Comment by tantaman** [comment] 2023-11-27 23:28
New release published. You should be all set. Note that I've published these under the `next` tag until I've had a chance to roll them into the various examples and demo apps to further verify the builds.

https://github.com/vlcn-io/js/discussions/39

**Comment by theboolean** [comment] 2023-11-28 15:11
Thank you @tantaman, @rhashimoto, and all the people involved in fixing this 🙏🏻

**Comment by tantaman** [comment] 2023-12-01 03:17
v0.16.0-next.2 is pretty solid at this point. There were a few bugs in v0.16.0-next.0 that are now fixed.

Will be making `next.2` the stable release soon.

**Closed by tantaman** 2023-12-01 03:17 UTC
